version: '3.8'

services:
  app:
    image: node:latest
    command: npm run dev
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - db
  